@alert__cpu.sql
@alert__tablespace_free_space.sql
@alert__fra_space.sql
@alert__resource_limit.sql
@alert__process_limit.sql
@alert__jobs.sql
@alert__startup_time.sql
@alert__dba_outstanding_alerts.sql
@alert__large_sorts.sql
@alert__arch_log_not_applied.sql
@alert__sort_space.sql
@alert__rman_status.sql
@alert__rman_running_long.sql
@alert__dataguard_status.sql
@alert__long_active_sql.sql
@alert__blocked_sessions.sql
@alert__low_sessions.sql
@alert__table_growth_rate.sql
@alert__new_large_segment.sql
@alert__sql_slow_not_normal.sql
@alert__new_accounts.sql
@alert__locked_accounts.sql
@alert__expiring_passwords.sql
@alert__datapump_not_running.sql
@alert__datapump_running_long.sql