exec drop_table('ai_provider');
exec drop_table('fuse_provider');
begin
   if not does_table_exist('fuse_provider') then 
      execute immediate '
      create table fuse_provider (
      provider_id number generated by default on null as identity cache 20 noorder nocycle nokeep noscale not null,
      provider_name varchar2(512) not null,
      provider_url varchar2(512) not null,
      provider_api_key varchar2(512) not null,
      created timestamp default systimestamp)';
   end if;
   add_primary_key('fuse_provider', 'provider_id');
   if not does_index_exist('fuse_provider_01') then
      execute immediate 'create unique index fuse_provider_01 on fuse_provider(provider_name)';
   end if;
end;
/

begin
   insert into fuse_provider (provider_name, provider_url, provider_api_key) values ('together', 'https://api.together.xyz/v1/chat/completions', fuse_config.together_api_key);
   insert into fuse_provider (provider_name, provider_url, provider_api_key) values ('anthropic', 'https://api.anthropic.com/v1/messages', fuse_config.anthropic_api_key);
end;
/

exec drop_table('ai_model');
exec drop_table('provider_model');
begin
   if not does_table_exist('provider_model') then 
      execute immediate '
      create table provider_model (
      model_id number generated by default on null as identity cache 20 noorder nocycle nokeep noscale not null,
      model_name varchar2(512) not null,
      -- Chat, Lang, Code, Image
      model_type varchar2(32) not null,
      provider_id number not null,
      context_length number not null,
      json_mode varchar2(1) default ''N'')';
   end if;
   add_primary_key('provider_model', 'model_id');
   if not does_constraint_exist('fk_provider_model_provider_id') then
      execute immediate 'alter table provider_model add constraint fk_provider_model_provider foreign key (provider_id) references fuse_provider(provider_id)';
   end if;
   if not does_index_exist('provider_model_01') then
      execute immediate 'create unique index provider_model_01 on provider_model(model_name)';
   end if;
end;
/

create or replace procedure add_model (
   p_model_name in varchar2,
   p_model_type in varchar2,
   p_provider_name in varchar2,
   p_context_length in number) is
begin

   insert into provider_model (
      model_name,
      model_type,
      provider_id,
      context_length) values (
      p_model_name,
      p_model_type,
      (select provider_id from fuse_provider where provider_name=p_provider_name),
      p_context_length);
end;
/

-- together.ai
exec add_model('codellama/CodeLlama-7b-Instruct-hf', 'Chat', 'together', 16384);
exec add_model('codellama/CodeLlama-34b-Instruct-hf', 'Chat', 'together', 16384);
exec add_model('mistralai/Mistral-7B-Instruct-v0.2', 'Chat', 'together', 32768);
exec add_model('google/gemma-7b-it', 'Chat', 'together', 8192);
exec add_model('databricks/dbrx-instruct', 'Chat', 'together', 32768);
-- Supports function calling and json_mode.
exec add_model('togethercomputer/CodeLlama-34b-Instruct', 'Chat', 'together', 16384);
exec add_model('mistralai/Mistral-7B-Instruct-v0.1', 'Chat', 'together', 8192);
exec add_model('mistralai/Mixtral-8x7B-Instruct-v0.1', 'Chat', 'together', 0);

-- anthropic.ai
exec add_model('claude-3-opus-20240229', 'Chat', 'anthropic', 200000);
exec add_model('claude-3-sonnet-20240229', 'Chat', 'anthropic', 200000);
exec add_model('claude-3-haiku-20240307', 'Chat', 'anthropic', 200000);


-- As of Apr 2024 together supports JSON mode for the following models.
update provider_model set json_mode='Y'
 where model_name in (
   'mistralai/Mixtral-8x7B-Instruct-v0.1', 
   'mistralai/Mistral-7B-Instruct-v0.1', 
   'togethercomputer/CodeLlama-34b-Instruct');

exec drop_table('ai_session');
exec drop_table('fuse_session');
begin
   if not does_table_exist('fuse_session') then 
      execute immediate '
      create table fuse_session (
      session_id number generated by default on null as identity cache 20 noorder nocycle nokeep noscale not null,
      session_name varchar2(512) not null,
      model_id number not null,
      max_tokens number default null,
      randomness number default null,
      pause number default null,
      total_tokens number default 0 not null,
      elapsed_seconds number default 0,
      call_count number default 0,
      status varchar2(32) default ''active'',
      created timestamp default systimestamp)';
   end if;
   add_primary_key('fuse_session', 'session_id');
   if not does_index_exist('fuse_session_01') then
      execute immediate 'create index fuse_session_01 on fuse_session(session_name)';
   end if;
   if not does_constraint_exist('fk_fuse_session_model_id') then
      execute immediate 'alter table fuse_session add constraint fk_fuse_session_model foreign key (model_id) references provider_model(model_id)';
   end if;
end;
/

exec drop_table('ai_session_prompt');
exec drop_table('session_prompt');
begin
   if not does_table_exist('session_prompt') then 
      execute immediate '
      create table session_prompt (
      session_prompt_id number generated by default on null as identity cache 20 noorder nocycle nokeep noscale not null,
      session_id number not null,
      start_time timestamp default systimestamp,
      end_time timestamp default null,
      elapsed_seconds number default 0,
      finish_reason varchar2(32) default ''n/a'',
      total_tokens number default 0 not null,
      prompt_role varchar2(32) not null,
      prompt clob not null,
      response_id varchar2(512) default null,
      schema clob default null,
      tools clob default null,
      function_name varchar2(128) default null,
      -- When 1 will not be included in prompt reconstruction.
      exclude number default 0,
      created timestamp default systimestamp)';
   end if;
   add_primary_key('session_prompt', 'session_prompt_id');
   add_foreign_key('session_prompt', 'session_id', 'fuse_session', 'session_id', true);
end;
/

exec drop_table('ai_plugin');

exec drop_table('request_queue');
begin
   if not does_table_exist('request_queue') then 
      execute immediate '
      create table request_queue (
      request_queue_id number generated by default on null as identity cache 20 noorder nocycle nokeep noscale not null,
      request_text clob not null,
      handler varchar2(512) default null,
      handled_timestamp timestamp default null,
      created timestamp default systimestamp,
      status varchar2(32) default ''active'')';
   end if;
end;
/




