@accounts_of_interest_view.sql
@active_sorts_view.sql
@all_sorts_view.sql
@arch_dest_status_time_view.sql
@archive_log_dist_view.sql
@asm_views.sql
@blocked_sessions_view.sql
@create_table_dist_view.sql
@instance_uptime_view.sql
@large_sorts_view.sql
@locked_objects_view.sql
@lockers_view.sql
@machine_last_call_day_pivot.sql
@process_limit_view.sql
@recycle_bin_info_view.sql
@resource_limit_view.sql
@rman_backup_job_details_view.sql
@rman_status_view.sql
@session_info_view.sql
@sga_info_view.sql
@sort_info_view.sql
@sparse_tables_view.sql
@standby_completion_time_views.sql
@table_growth_rates_view.sql
@table_size_summary_view.sql
@table_stats_view.sql
@tsinfo_view.sql
@unified_audit_review_view.sql
@unq_jobs_failing_in_last_24hr.sql
@username_last_call_day_pivot.sql
@program_last_call_day_pivot.sql
